# Site settings
title: Freelancer
email: VirtualStarWatch@gmail.com
url: https://SarahBass.github.io
description: "Virtual Star Studios creates games and apps for all ages!"
keywords: "Virtual, Star, Pet, Watch, Wear Os, Sarah Bass"
skills: "Sarah Bass App Developer - Graphic Artist - Computer Science A.A."
meta_author: Bass Sarah

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: Sarah Bass

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: Android Google Play
    url:https://play.google.com/store/apps/dev?id=8905289373249083173
  - title: Instagram
    url: https://www.instagram.com/koonchki/?hl=en
  - title: github
    url: https://github.com/SarahBass
  - title: Fitbit Developer
    url: https://gallery.fitbit.com/developer/850971bc-7265-471f-81f9-608d179f4ddd
  - title: Leetcode
    url: 
  - title: Linkedin
    url: 


# Postal address (add as many lines as necessary)
address:
  - line: Orange County
  - line: California

# Credits content
credits: '<a href="http://startbootstrap.com">Start Bootstrap</a>'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
